### ISSUE TITLE
Pandemic Modeling Page

### ISSUE THREAD

**Issue by AndreasInk** [Vito-Research/Vito-Visualization#13]
Transfer main.py to a new pandemic modeling page...
https://github.com/Vito-Research/covasim

main.py contains the Streamlit code

**Comment by ghost** [comment]
Hi! I wanna start to contribute with projects open source. I just a junior, buy i am interest in this project...
Can you assign to me this enhancement and give some of context?
Thanks!

**Comment by AndreasInk** [comment]
Sure thing! I'll do that in a bit and at you when I create an issue with more context.  Thanks for wanting to help!

**Comment by AndreasInk** [comment]
> Hi! I wanna start to contribute with projects open source. I just a junior, buy i am interest in this project...
> Can you assign to me this enhancement and give some of context?
> Thanks!

Created an issue...
https://github.com/Vito-Research/Vito-Visualization/issues/14

Thanks again!

**Comment by AndreasInk** [comment]
Complete!
