### ISSUE TITLE
Main.py UI Enhancements

### ISSUE THREAD

**Issue by AndreasInk** [Vito-Research/Vito-Visualization#14]
- Add an image (or two) from the readme (https://github.com/Vito-Research) to Main.py (https://github.com/Vito-Research/Vito-Visualization/blob/main/main.py)
- Add the following bullet points below the image(s)...
This web app is designed to illustrate how Vito works, We are a group of students developing open-source tools to fight pandemics, If you'd like to contribute... click here (insert a link to this repo)
(, = new bullet)

Here are some helpful docs, streamlit is the UI framework for Python...
https://docs.streamlit.io/library/cheatsheet

@tuxedo309

Also, please create a separate branch or fork the repo to contribute.

Thanks again for wanting to assist!

**Comment by AndreasInk** [comment]
Btw, if you need help with any help, feel free to reach out, happy to help @tuxedo309

**Comment by grantranda** [comment]
@AndreasInk Here are a couple screenshots of the main page using different images. Is there a particular image you would prefer, and are there any changes to the layout that should be made?

![1](https://user-images.githubusercontent.com/48031522/182920466-db22ad0f-d5d1-4617-960b-ca73970335e0.png)
![2](https://user-images.githubusercontent.com/48031522/182920484-1063fda1-c98b-4d91-bb23-a6552b2ada55.png)

**Comment by AndreasInk** [comment]
Looks good! I think I prefer the first, thanks for making that change.

**Comment by AndreasInk** [comment]
Layout wise, I think it's good too :)
