### ISSUE TITLE
Kotlin and Swift VS Python

### ISSUE THREAD

**Issue by AndreasInk** [Vito-Research/Vito-Visualization#2]
- Compare Kotlin and Swift algorithms to the stable Python algorithm developed by a study (NightSignal)
- Create an API to get the results for Swift and Kotlin
- Python code is executed within Streamlit
- Attempt to execute Swift and Kotlin code in Streamlit, if not possible, @AndreasInk will try to make a workaround

**Comment by EthanCloin** [comment]
@AndreasInk thanks for making this issue! A few questions below :)

* Am I understanding correctly that you have 3 implementations of 1 algorithm (NightSignal for iOS, Android, and Web) and you want to test whether they all produce identical results? Is there an existing set of test data with expected results for this?
* Are there any existing Python->iOS/Android API's in this project? If yes, I'll aim to follow a similar style and steal any reusable logic.
* What do you mean by "execute Swift and Kotlin in Streamlit"? From what I see on Streamlit docs, it's a python framework for displaying data on web apps without writing HTML/CSS/JS and doesn't have anything geared to mobile.

**Comment by AndreasInk** [comment]
Yes, there are three implementations, two I made built-in Swift and Kotlin, and one built by a research study in Python.  Yes, the goal is to produce identical results and there is an existing dataset, here's the most up-to-date dataset that includes the iOS algorithm's predictions (working on the Kotlin version still)...
https://github.com/Vito-Research/Vito-Visualization/tree/main/sample_data/Healthv6v2

We tend to use a lot of NumPy, pandas, and streamlit, but other than that, we are fairly open, but feel free to reuse whatever code.

I doubt it could work too for the exact reason you mentioned, I just haven't researched if there was somehow support for Swift or Kotlin.  I was hoping that the servers Streamlit has Swift and Kotlin installed and there might be a way to run some code in those languages but it's not likely.  

I'm also going to add more issues in the AM, just need to rest a bit so I think a bit more clearly.

Thanks again for your interest!

**Comment by AndreasInk** [comment]
Found a solution for the Swift side, there's a backend called Vapor that can run Swift code in Heroku so I made a new repo for that

**Comment by AndreasInk** [comment]
Swift side implemented, going to close and create a new issue for the Kotlin side
