### ISSUE TITLE
General Maintenance   

### ISSUE THREAD

**Issue by AndreasInk** [Vito-Research/Vito-Visualization#5]
As @EthanCloin suggested general maintenance would be great! 

Here's what would be great...
requirements.txt rather than a shell script
Comment code
More comprehensive readme

As always feel free to add additional maintenance items :)

**Comment by EthanCloin** [comment]
requirements.txt is updated as of #6 ! Leaving this open until other items are addressed

**Comment by AndreasInk** [comment]
> requirements.txt is updated as of #6 ! Leaving this open until other items are addressed

Thanks!

**Comment by AndreasInk** [comment]
Closing as it's complete
